server:
  port: 8011
  tomcat:
          uri-encoding: UTF-8
          max-threads: 1000
          min-spare-threads: 30
  connection-timeout: 5000

spring:
  # 环境
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
    encoding:
      force: true
      charset: utf-8
      enabled: true
  redis:
    host: r-wz93b87d7774bfc4.redis.rds.aliyuncs.com # host ,默认 localhost
    port: 6379 # 端口号，默认6379
    pool:
    # 设置都是默认值，可以按需求设计
      max-active: 8 # 可用连接实例的最大数目，默认值为8；如果赋值为-1，则表示不限制；
      max-idle: 8  # 控制一个pool最多有多少个状态为idle(空闲的)的redis实例，默认值也是8。
      max-wait: -1 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。
      min-idle: 0 # 控制一个pool最少有多少个状态为idle(空闲的)的redis实例，默认值为0。
    timeout: 0 # 连接超时时间 单位 ms，默认为0
    password: zk@595165463 # 密码，根据自己的 redis 设计，默认为空
  session:
    store-type: redis
  data:
    mongodb:
      uri: mongodb://wuwii:123456@localhost:27017/learn

  #resources: # 指定静态资源的路径
   # static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: com.wuwii.module.**.entity
    typeHandlersPackage: com.wuwii.module.sys.common.handle,com.wuwii.module.task.common.handle


pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# jwt 配置
jwt:
  # 加密密钥
  secret: 61D73234C4F93E03074D74D74D1E39D9 #blog.wuwii.com
  # token有效时长
  expire: 7 # 7天，单位天
  # token 存在 header 中的参数
  header: token

# 用户的 token 的有效时间
sys:
  user-token:
    expire: 43200 # token 有效时间为 12 小时 单位 s

